import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Banner from "@/components/banner";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card";
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const handleOnBannerBtnClick = () => {
    console.log("button");
    router.push('/you');
  }
  return (
    <>
      <Head>
        <title>Happy Birthday!!!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>
          Happy Birthday! 
        </h1>
      {/* <p className={styles.subTitle}>I am celebrating the coolest person to be born- my best friend. Happy Birthday to.....! May the love and friendship you've shared with me come back to you in abundance on your special day. May the universe fulfil all your wishes this year just as it aligned to bring you into this world on this day!</p> */}
      <p className={styles.subTitle}>Happy Birthday to the best part of my college days! Hope your day is as amazing as you are!"</p>

        <div className={styles.heroimage}>
          <Image src="/static/3.png" width={700} height={300} />
        </div>
        <Banner
          buttonText="Memories"
          handleOnClick={handleOnBannerBtnClick}
        />
      </main>
    </>
  );
}
